### PR TITLE
director example

### PR DESCRIPTION
**Pull request by ihrankouski**
An attempt to implement a "Director" component that is responsible for allocation of DGSes (from Agones fleet) for successful matches.
- It is designed currently to work with single profile. 
- This director can handle "partial" matches ("backfills"). When received rosters have some empty cells, the director tries to fill them out: it organizes all such rosters into a new profile (with all other properties the same as in original one) and sends it to BE API again, then assigns the newly matched players to the originally allocated GS. And then repeats this again if needed.

Also there are slightly modified versions of clientloadgen and frontendclient there.

### CODE REVIEW

**Comment by jeremyje** [comment]
Let me know when this is ready for review.

**Comment by ihrankouski** [comment]
Actually you are welcome to review this. It must be working despite the TODOs in the code: just not all corner cases are handled so far.

**Comment by jeremyje** [comment]
Can you sync this PR and mark it read for review?

**Comment by jeremyje** [comment]
Merge conflicts. CI via Make just got submitted should provide better regression coverage.

**Comment by sawagh** [comment]
Given that v0.6 is changing all the APIs and services, this PR may already be deprecated. I ll decline this PR for now and once we have v0.6 Services ready, this PR can be re-worked into the new APIs. I ve syncd offline with Ilya and am closing this PR for now.

**Pull request closed without merging**
