### PR TITLE
Fix local cloud build error

### LINKED ISSUE #218: Failed to run local-cloud-build
Received an error when running `make local-cloud-build`.

`2019/04/16 17:14:39 Error merging substitutions and validating build: Error validating build: key "_GCB_POST_SUBMIT" in the substitution data is not matched in the template                            
`

### PR DESCRIPTION
**Pull request by yfei1**
Local cloud build failed because there are unused substitutions defined in cloudbuild.yaml.

Resolves #218

### CODE REVIEW

**Comment by jeremyje** [comment]
Is there something broken with your checkout? Maybe a bad merge or something. I don't see how this is fixing a problem may introduce something. I just checked the code the variable is propagated properly.

**Comment by yfei1** [comment]
Are you able to run `make local-cloud-build` locally? I checked out a new branch and it seems like the build build attempt still failed.

    yufanfei@yufanfei:~/go/src/github.com/GoogleCloudPlatform/open-match$ make local-cloud-build
    cloud-build-local --config=cloudbuild.yaml --dryrun=false  --substitutions SHORT_SHA=454a3d6,_GCB_POST_SUBMIT=0 .
    2019/04/17 08:59:06 Warning: there are left over step containers from a previous build, cleaning them.
    2019/04/17 08:59:07 Warning: a network is left over from a previous build, cleaning it.
    2019/04/17 08:59:07 Warning: there are left over step volumes from a previous build, cleaning it.
    2019/04/17 08:59:07 Warning: The server docker version installed (18.09.3) is different from the one used in GCB (18.09.0)
    2019/04/17 08:59:07 Warning: The client docker version installed (18.09.3) is different from the one used in GCB (18.09.0)
    2019/04/17 08:59:09 Error merging substitutions and validating build: Error validating build: key "_GCB_POST_SUBMIT" in the substitution data is not matched in the template
    Makefile:173: recipe for target 'local-cloud-build' failed

**Comment by jeremyje** [comment]
Argh cloud build prod thinks this is fine but not local. The issue is that there's no target that uses it. I commented it out. I'll approve for now.

**Comment by jeremyje** [comment]
So there's a simpler solution here. Just modify `cloudbuild.yaml` and uncomment `Deploy: Website` target.

**Comment by yfei1** [comment]
> So there's a simpler solution here. Just modify `cloudbuild.yaml` and uncomment `Deploy: Website` target.

I'll fix it this way

**Pull request merged**
