### PR TITLE
Update .gcloudignore to include .gitignore's filters so that Cloud Bu…

### PR DESCRIPTION
**Pull request by jeremyje**
…ild packages don't upload binaries.

### CODE REVIEW

**Comment by ihrankouski** [comment]
One thing regarding this is that current .gitignore has dangerous line: https://github.com/GoogleCloudPlatform/open-match/blob/040wip/.gitignore#L28
This may lead to broken images in theory (and I recall it was the case once in the past)

**Comment by jeremyje** [comment]
> One thing regarding this is that current .gitignore has dangerous line: https://github.com/GoogleCloudPlatform/open-match/blob/040wip/.gitignore#L28
> In future this may lead to broken images in theory (and I recall it was the case once in the past).

That's strange why .json files would get excluded but I did remove all of the json configs in https://github.com/GoogleCloudPlatform/open-match/commit/1847f795719460da17eb8552d36f1e7d9178296a

**Comment by joeholley** [comment]
> > One thing regarding this is that current .gitignore has dangerous line: https://github.com/GoogleCloudPlatform/open-match/blob/040wip/.gitignore#L28
> > In future this may lead to broken images in theory (and I recall it was the case once in the past).
> 
> That's strange why .json files would get excluded but I did remove all of the json configs in [1847f79](https://github.com/GoogleCloudPlatform/open-match/commit/1847f795719460da17eb8552d36f1e7d9178296a)

This is so that developers can maintain local copies of all the build and deploy `json` files without concern about them getting included in commits, since almost every file with a `json` or `yaml` extension requires updating with developer-specific registries and image names when doing local development.  Open to suggestions but needs a reasonably easy solution.

**Comment by jeremyje** [comment]
I think the ideal solution here is to have some presubmit (Cloud Build) script that would verify that files are good.
We could also change the deployment system to have a designated experimental deployment directory and ignore the files in there.

How feasible is this?

**Comment by jeremyje** [comment]
I got bit by the *.json ignore rule. Is there specific directories that we can reduce this filter to? I'd propose we remove *.json and see what specific directories/files are problematic and filter those out specifically.

**Pull request merged**
