### PR TITLE
Merge 040wip into master.

### PR DESCRIPTION
**Pull request by jeremyje**
There will be a follow up PR to cleanup some of the docs and prepare to cut v0.4.0.

### CODE REVIEW

**Comment by ihrankouski** [comment]
I've signed CLA already, and confirm that I'm okay with my commits being contributed to this project.

**Comment by jeremyje** [comment]
Manually verified the CLA agreements, sorry for the confusion. Gave feedback to the CLA team.

**Comment by jeremyje** [comment]
https://github.com/GoogleCloudPlatform/open-match/issues/136 is the bug tracking this.

**Pull request merged**
